name: Test all versions

on:
  push:
    branches:
      - main

concurrency:
  group: tests
  cancel-in-progress: true

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install packages
        run: yarn install --immutable

      - name: Upload to use with tests
        uses: actions/upload-artifact@v3
        with:
          name: installed-project
          path: ./

  test-react-16:
    name: Test React ^16
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Upload to use with tests
        uses: actions/download-artifact@v3
        with:
          name: installed-project

      - name: Test
        run: yarn test:react-16

  test-react-17:
    name: Test React ^17
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: "17"

      - name: Upload to use with tests
        uses: actions/download-artifact@v3
        with:
          name: installed-project

      - name: Test
        run: yarn test:react-17

  test-react-18:
    name: Test React ^18
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Upload to use with tests
        uses: actions/download-artifact@v3
        with:
          name: installed-project

      - name: Test
        run: yarn test:react-18
