name: Test all versions

on:
  push:
    branches:
      - main

concurrency:
  group: tests
  cancel-in-progress: true

jobs:
  test-react-16:
    name: Test React ^16
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install packages
        run: yarn install --immutable

      - name: Test
        run: yarn test:react-16

  test-react-17:
    name: Test React ^17
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install packages
        run: yarn install --immutable

      - name: Test
        run: yarn test:react-17

  test-react-18:
    name: Test React ^18
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install packages
        run: yarn install --immutable

      - name: Test
        run: yarn test:react-18
